### ISSUE TITLE
Axios error 

### ISSUE THREAD

**Issue by BrothaGithubber** [Fannovel16/fancaps-scraper#2]
saveDir: '/content/fancaps-images',
  numOfPromises: 100,
  forceUnlimitedPromises: true,
  skipNLastPages: 2,
  writeMetadata: false,
  readMetadata: false,
  dontDownloadImages: false,
  disableProgressBar: false,
  colab: true
}
(node:2033) UnhandledPromiseRejectionWarning: AxiosError: Request failed with status code 403
    at settle (/content/fancaps-scraper/node_modules/axios/dist/node/axios.cjs:1859:12)
    at BrotliDecompress.handleStreamEnd (/content/fancaps-scraper/node_modules/axios/dist/node/axios.cjs:2723:11)
    at BrotliDecompress.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2033) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:2033) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Downloaded images:
find: ‘/content/fancaps-images’: No such file or directory
0

**Comment by K1ssSh0t** [comment]
same here
